name: Build and Deploy Prod

on:
  push:
    branches: [ main ]

env:
  AppName: mobiledatausage
  Location: westeurope

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Publish
      run: dotnet publish --no-restore -o publish -c Release

    - name: Publish
      run: dotnet publish --no-restore -o publish -c Release

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resource group
      uses: Azure/cli@v1
      continue-on-error: true
      with:
        inlineScript: |
          az group create --name rg-${{ env.AppName }} --location ${{ env.Location }}

    - name: Deploy infra
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg-${{ env.AppName }}
        template: ../biceps/azure-deployment.bicep
        parameters: >
          appNameSuffix=${{ env.AppName }} 
          providerEmail=${{ secrets.APPCONFIG_PROVIDEREMAIL }} 
          providerPassword=${{ secrets.APPCONFIG_PROVIDERPASSWORD }}
          telegramUsers=${{ secrets.TELEGRAMAPICONFING_TELEGRAMUSERS }}
          telegramAccessToken=${{ secrets.TELEGRAMAPICONFING_ACCESSTOKEN }}
          cronoTimerSchedule='0 */15 * * * *'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: fn-${{ env.AppName }}
        package: './publish'