name: Build and Deploy Prod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AppName: mobiledatausage
  Location: westeurope
  TelegramEndpoint: https://api.telegram.org/bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Publish
      run: dotnet publish --no-restore -o publish -c Release

    - name: Publish
      run: dotnet publish --no-restore -o publish -c Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          publish
          .github/biceps
          .github/scripts
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build    

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - name: Create resource group
      uses: Azure/cli@v1
      continue-on-error: true
      with:
        inlineScript: |
          az group create --name rg-${{ env.AppName }} --location ${{ env.Location }}

    - name: Deploy infra
      uses: azure/arm-deploy@v1
      id: deployinfra
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg-${{ env.AppName }}
        template: artifact/.github/biceps/azure-deployment.bicep
        parameters: >
          appNameSuffix=${{ env.AppName }}
          providerEmail=${{ secrets.APPCONFIG_PROVIDEREMAIL }} 
          providerPassword=${{ secrets.APPCONFIG_PROVIDERPASSWORD }}
          telegramApiEndpoint=${{ env.TelegramEndpoint }}
          telegramUserOnePhoneNumber=${{ secrets.TELEGRAMAPICONFING_TELEGRAMUSERONEPHONENUMBER }}
          telegramUserOneChatId=${{ secrets.TELEGRAMAPICONFING_TELEGRAMUSERONECHATID }}
          telegramUserTwoPhoneNumber=${{ secrets.TELEGRAMAPICONFING_TELEGRAMUSERTWOPHONENUMBER }}
          telegramUserTwoChatId=${{ secrets.TELEGRAMAPICONFING_TELEGRAMUSERTWOCHATID }}
          telegramAccessToken=${{ secrets.TELEGRAMAPICONFING_ACCESSTOKEN }}
          cronoTimerSchedule="0 */15 * * * *"

    - name: Setup MobileDataCommandDispatcherFunction telegram webhook
      uses: azure/powershell@v1
      with:
        azPSVersion: latest
        inlineScript: >
          ./artifact/.github/scripts/setup-telegram-webhook.ps1 
          ${{ env.TelegramEndpoint }} 
          ${{ secrets.TELEGRAMAPICONFING_ACCESSTOKEN }} 
          "${{ steps.deployinfra.outputs.functionBaseUrl }}/MobileDataCommandDispatcherFunction"
          ${{ steps.deployinfra.outputs.functionAppName }}

    - name: Setup MobileDataCommandDispatcherFunction telegram commands
      shell: pwsh
      run: >
        ./artifact/.github/scripts/setup-telegram-commands.ps1 
        ${{ env.TelegramEndpoint }} 
        ${{ secrets.TELEGRAMAPICONFING_ACCESSTOKEN }}
        ./artifact/.github/scripts/bot-commands.json

    - name: Deploy azure functions code
      uses: Azure/functions-action@v1.4.4
      with:
        app-name: ${{ steps.deployinfra.outputs.functionAppName }}
        package: artifact/publish